included:
  - questions

analyzer_rules:
  - unused_import

disabled_rules:
  - cyclomatic_complexity
  - vertical_whitespace_closing_braces
  - indentation_width
  - attributes
  - trailing_whitespace

opt_in_rules:
  - extension_access_modifier
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - indentation_width
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - yoda_condition
  - large_tuple
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - file_name_no_space
  - flatmap_over_map_reduce
  - for_where

force_try: warning
function_body_length:
    warning: 130

legacy_hashing: error

identifier_name:
  min_length: 2
  max_length: 70
  validates_start_with_lowercase: "warning"
  allowed_symbols:
    - "_"
  excluded:
    - i
    - x
    - y
    - z
    - r
    - e
    - j
    - s
    - f

type_name:
  min_length: 1
  max_length: 70

nesting:
  type_level: 2

type_body_length:
  warning: 350
  error: 500

large_tuple:
  warning: 5
  error: 5

line_length:
  warning: 140
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true

private_over_fileprivate:
  validate_extensions: true

vertical_whitespace:
  max_empty_lines: 2

